"""Id mudado para string e date acrescentado

Revision ID: 5dec580ba282
Revises: 97ba63107b02
Create Date: 2025-10-19 20:22:56.214498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dec580ba282'
down_revision: Union[str, Sequence[str], None] = '97ba63107b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('date', sa.DateTime(), nullable=True))
    op.alter_column('emails', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('emails', 'date')
    # ### end Alembic commands ###
